* declaration for the long text
DATA: ICDTXT_ZBUGTRACKER
     TYPE STANDARD TABLE OF CDTXT.
DATA: UPD_ICDTXT_ZBUGTRACKER TYPE C.

* table with the NEW content of: ZBT_ATTACHMENT
DATA: XZBT_ATTACHMENT
        TYPE STANDARD TABLE OF
        YZBT_ATTACHMENT.

* table with the OLD content of: ZBT_ATTACHMENT
DATA: YZBT_ATTACHMENT
        TYPE STANDARD TABLE OF
        YZBT_ATTACHMENT.

DATA: UPD_ZBT_ATTACHMENT TYPE C.

* workaera_new of ZBT_BUG
DATA: ZBT_BUG
        TYPE ZBT_BUG.
* workaera_old of OLD_BUG
DATA: OLD_BUG
        TYPE ZBT_BUG.
DATA: UPD_ZBT_BUG TYPE C.


* table with the NEW content of: ZBT_BUGCOMMENT
DATA: XZBT_BUGCOMMENT
        TYPE YZBT_BUGCOMMENTS.

* table with the OLD content of: ZBT_BUGCOMMENT
DATA: YZBT_BUGCOMMENT
        TYPE YZBT_BUGCOMMENTS.

DATA: UPD_ZBT_BUGCOMMENT TYPE C.

* table with the NEW content of: ZBT_BUGSECCION
DATA: XZBT_BUGSECCION
        TYPE STANDARD TABLE OF
        YZBT_BUGSECCION.

* table with the OLD content of: ZBT_BUGSECCION
DATA: YZBT_BUGSECCION
        TYPE STANDARD TABLE OF
        YZBT_BUGSECCION.

DATA: UPD_ZBT_BUGSECCION TYPE C.

* table with the NEW content of: ZBT_PROGRAMS
DATA: XZBT_PROGRAMS
        TYPE STANDARD TABLE OF
        YZBT_PROGRAMS.

* table with the OLD content of: ZBT_PROGRAMS
DATA: YZBT_PROGRAMS
        TYPE STANDARD TABLE OF
        YZBT_PROGRAMS.

DATA: UPD_ZBT_PROGRAMS TYPE C.

* table with the NEW content of: ZBT_TRANSPORTER
DATA: XZBT_TRANSPORTER
        TYPE STANDARD TABLE OF
        YZBT_TRANSPORTER.

* table with the OLD content of: ZBT_TRANSPORTER
DATA: YZBT_TRANSPORTER
        TYPE STANDARD TABLE OF
        YZBT_TRANSPORTER.

DATA: UPD_ZBT_TRANSPORTER TYPE C.

