*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 17.05.2010 at 23:26:01 by user BCUSER
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZBUGTRACKERMODELTOP.              " Global Data
  INCLUDE LZBUGTRACKERMODELUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZBUGTRACKERMODELF00                    . " subprograms
  INCLUDE LZBUGTRACKERMODELI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZBUGTRACKERMODELF...              " Subprograms
* INCLUDE LZBUGTRACKERMODELO...              " PBO-Modules
* INCLUDE LZBUGTRACKERMODELI...              " PAI-Modules
